name: triton_vs_cuda_fsa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pytorch
  - cudatoolkit
  - pip:
    - triton
